apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  labels:
    deploy: todo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo  
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: "todov1registry.azurecr.io/todov1"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
      imagePullSecrets:
      - name: todoapisecret
---
apiVersion: v1
kind: Service
metadata:
  name: todo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: todo